### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by KingEnderBrine**
I keep finding small things

### CODE REVIEW

**Comment by nesrak1** [comment]
> [Fix AssetsView LZ4 decompression](https://github.com/nesrak1/AssetsTools.NET/pull/91/commits/85735450ef9c34b753f48b9762f5c55b5c1608c3)

This was an intentional change after LZ4 block loading was implemented since the bundle isn't required to be fully decompressed anymore. Maybe you could argue this dialog should still appear, but I decided most people won't care to decompress it fully when it loads perfectly fast already.

> [Fix adding broken type to the type tree when using AssetsRemover](https://github.com/nesrak1/AssetsTools.NET/pull/91/commits/cc4826a05d0d606f5a521a01f9d5b05856474592)

I didn't realize it made broken types in the type tree? I've been doing this since the beginning but you're right that this should only apply to added assets.

**Comment by KingEnderBrine** [comment]
> This was an intentional change after LZ4 block loading was implemented since the bundle isn't required to be fully decompressed anymore. Maybe you could argue this dialog should still appear, but I decided most people won't care to decompress it fully when it loads perfectly fast already.

Well, then It doesn't work in a different way, because I do have lz4 bundle and it just crashes AssetView because it's not decompressed

**Comment by KingEnderBrine** [comment]
I will try to investigate more then

**Comment by KingEnderBrine** [comment]
Reverted lz4 commit as it was a different issue fixed in 4e7a9c150f7cac5d8e5bebc46dece65007da4cc2

**Pull request merged**
