### PR TITLE
feat: support ASTC texture decode

### PR DESCRIPTION
**Pull request by liuxinyumocn**
Support ASTC texture decode, and there is a default solution for decoding failure.

### CODE REVIEW

**Comment by nesrak1** [comment]
I can accept it for now, but I plan to use [AssetRipper's TextureDecoder library](https://github.com/AssetRipper/TextureDecoder) (the mafaca decoders like the one you used but all of them in one place) in the future and make it a nuget package.

**Comment by liuxinyumocn** [comment]
AssetRipper's TextureDecoder library and mafaca decoders are both good, but they do not support decoding HDR. The best way is to use the dynamic link library, which is written through c++.

**Comment by nesrak1** [comment]
Having multiple options for managed/unmanaged decoding is the plan, where you can use a fast and more featureful native but less xplat library or a slower more xplat version. Nothing has been written for it though, just planned.

**Comment by liuxinyumocn** [comment]
Thank you very much.

**Comment by nesrak1** [comment]
AssetRipper TextureDecoder is in the Texture project now.

**Pull request closed without merging**
