### PR TITLE
Fix MonoCecilTempGenerator serializing things it shouldn't

### PR DESCRIPTION
**Pull request by KingEnderBrine**
After discord conversation about dictionary being counted as serializable while it shouldn't also decided to check what about other collections including non-generic. And they also shouldn't be serialized and lots of more stuff shouldn't

### CODE REVIEW

**Comment by nesrak1** [comment]
Blacklisting the assembly might be a solution, but I think what actually happens is the Dictionary itself is blacklisted. See https://github.com/Unity-Technologies/UnityCsReference/blob/master/Tools/Unity.SerializationLogic/UnitySerializationLogic.cs#L449.

**Comment by KingEnderBrine** [comment]
Well, as I said, other collections are also are not serialized even non-generic ones even though they are marked as serializable. KeyValuePair (in Unity 2022) is also not serialized, while it should've been. So Unity definitely does have some blacklist, since in 99% of system classes/structs that are marked as serializable the actual field with value is private which doesn't work for Unity standards so it wouldn't be serialized correctly anyway.

**Comment by KingEnderBrine** [comment]
Ah that a one way to do it https://github.com/Unity-Technologies/UnityCsReference/blob/3ff5b7b7ff1dac2a8c52b74b9fb7148a7f4e9a15/Tools/Unity.SerializationLogic/UnitySerializationLogic.cs#L569-L570 but we don't know for sure is that what's happening on the native side

**Comment by KingEnderBrine** [comment]
I actually though about doing it that way, but in Unity 2019 it did serialize field of a `System.Drawing.Rectangle` type even though it didn't show any fields because they are private, while Unity 2022 didn't even serialize it. So that can't be what they did in 2019 or earlier

**Pull request merged**
